### ISSUE TITLE
Dialogue Engine [meta]

### ISSUE THREAD

**Issue by MichaelBelousov** [alternis-io/AlternisFlow-WebEditor#1]
Create a "dialogue" engine that reads _dialogue files_ (probably a JSON schema)
and 

- [x] create a JSON schema for the json flavor of dialogue files
- [x] create a library with a C API (see [README](https://github.com/MichaelBelousov/DialogueMiddleware#c-api) c-api section for some ideatation)
- [x] build the project for all operating systems, architectures, and web assembly (woohoo zig)
- [x] add callback registering to c API
- [x] add variable editing to c api
- [x] handle all nodes
- [x] add participant, variable information
